"""Added User Invite Token Table

Revision ID: 42860906ea94
Revises: 3a7a75f14a1b
Create Date: 2019-04-25 19:34:49.976630

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "42860906ea94"
down_revision = "3a7a75f14a1b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_invite_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_datetime",
            sa.DateTime(),
            server_default=sa.text("(now() at time zone 'utc')"),
            nullable=False,
        ),
        sa.Column("token_issuer_id", sa.Integer(), nullable=False),
        sa.Column("token_user_id", sa.Integer(), nullable=True),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column(
            "used", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("used_datetime", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["token_issuer_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["token_user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_invite_tokens_token_issuer_id"),
        "user_invite_tokens",
        ["token_issuer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_invite_tokens_token_user_id"),
        "user_invite_tokens",
        ["token_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_invite_tokens_token_user_id"), table_name="user_invite_tokens"
    )
    op.drop_index(
        op.f("ix_user_invite_tokens_token_issuer_id"), table_name="user_invite_tokens"
    )
    op.drop_table("user_invite_tokens")
    # ### end Alembic commands ###
