"""added Messages and Conversation table

Revision ID: c8b1301dc571
Revises: 42860906ea94
Create Date: 2019-04-28 23:14:50.765686

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c8b1301dc571"
down_revision = "42860906ea94"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_datetime",
            sa.DateTime(),
            server_default=sa.text("(now() at time zone 'utc')"),
            nullable=False,
        ),
        sa.Column("user_id_1", sa.Integer(), nullable=False),
        sa.Column("user_id_2", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id_1"], ["users.id"]),
        sa.ForeignKeyConstraint(["user_id_2"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversations_user_id_1"), "conversations", ["user_id_1"], unique=False
    )
    op.create_index(
        op.f("ix_conversations_user_id_2"), "conversations", ["user_id_2"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_datetime",
            sa.DateTime(),
            server_default=sa.text("(now() at time zone 'utc')"),
            nullable=False,
        ),
        sa.Column(
            "sent_datetime",
            sa.DateTime(),
            server_default=sa.text("(now() at time zone 'utc')"),
            nullable=False,
        ),
        sa.Column("from_user_id", sa.Integer(), nullable=False),
        sa.Column("to_user_id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"]),
        sa.ForeignKeyConstraint(["from_user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["to_user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_messages_conversation_id"),
        "messages",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_messages_from_user_id"), "messages", ["from_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_messages_to_user_id"), "messages", ["to_user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_to_user_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_from_user_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_conversations_user_id_2"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_user_id_1"), table_name="conversations")
    op.drop_table("conversations")
    # ### end Alembic commands ###
